/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.interfase;

import com.negocio.Archivo;
import com.negocio.Consulta;
import java.awt.Dimension;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tutor
 */
public class Borrar extends javax.swing.JDialog {

    /**
     * Creates new form Borrar
     */
    public Borrar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        String fecha = null;
        Date d = new Date();
        SimpleDateFormat sdf= new SimpleDateFormat("dd-MM-yyyy h:mm a");
        fecha=sdf.format(d).toString();
        ResultSet resultado=null;
        ResultSet resultado1=null;
        Consulta instconsulta= new Consulta();
        resultado= instconsulta.realiza_Consulta("registro");
        DefaultTableModel searchListModel = new DefaultTableModel();
        this.tbl_registro.setModel(searchListModel);
        searchListModel.addColumn("CEDULA");
        searchListModel.addColumn("NOMBRE");
        searchListModel.addColumn("CODIGO");
        searchListModel.addColumn("NUMERO DE OBJ PRESTADOS");
        //ASIGNAR TAMAÑO A CADA COLUMNA
        tbl_registro.getColumnModel().getColumn(0).setPreferredWidth(80);
        tbl_registro.getColumnModel().getColumn(1).setPreferredWidth(80);
        tbl_registro.getColumnModel().getColumn(2).setPreferredWidth(40);
        tbl_registro.getColumnModel().getColumn(3).setPreferredWidth(120);
        try{
            while(resultado.next()){
                //Se crea un array q sera una de las filas de la tabla
                Object [] fila = new Object[4];//Hay 4 columnas en la tabla
                resultado1= instconsulta.numero_Registro(resultado.getObject(1).toString());
                if(resultado1.next()==false){
                    fila[3]="0";
                }else{
                    //resultado1 es solo una fila y si no hay elementos no hay filas si .next()=false no hay filas si .next()=true existe una fila con datos
                    fila[3]=resultado1.getObject(2);                    
                }       
                for(int i=1; i<=3;i++){
                    fila[i-1] = resultado.getObject(i);
                }//El primer indice en rs es el 1 no el cero por eso se suma 1
                // Se añade al modelo la Fila completa
                searchListModel.addRow(fila);
            }
        }catch(SQLException e){
            System.out.println("Error de MySQL: "+e.getMessage());
        }
    }

    private String Fecha()
    {
        String fecha = null;
        Date d = new Date();
        SimpleDateFormat sdf= new SimpleDateFormat("dd-MM-yyyy h:mm a");
        fecha=sdf.format(d).toString();
        return fecha;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_registro = new javax.swing.JTable();
        btn_borrar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LabLEND 1.0-Prestamos y Estudiantes");

        jLabel1.setText("PRESTAMOS REGISTRADOS");

        tbl_registro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "NO SE ENCONTRARON DATOS"
            }
        ));
        jScrollPane1.setViewportView(tbl_registro);

        btn_borrar.setText("Borrar Registro");
        btn_borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_borrarMouseClicked(evt);
            }
        });

        btn_editar.setText("Editar Registro");
        btn_editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editarMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resources/facu.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_borrar, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(btn_editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_borrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_borrarMouseClicked
      int fila = tbl_registro.getSelectedRow();
      Archivo intArc=new Archivo();//escribe el archivo
      ResultSet resultado=null;
      if (fila != -1) {
        int k =  JOptionPane.showConfirmDialog(rootPane, "Borrar Todos los registros de este estudiante??", "BORRAR REGISTROS", 1);
        if(JOptionPane.OK_OPTION==k){
          String ced=null;
          Object obj=null;
          Consulta intCon=new Consulta();
          DefaultTableModel model = (DefaultTableModel)tbl_registro.getModel();        
          obj=model.getValueAt(tbl_registro.getSelectedRow(),0);
          Object obj1[]=new Object[4];
          ced=obj.toString();
          int p=0, e=0;
          resultado= intCon.consulta_prestamos(ced);
              try {
                  while(resultado.next()){
                      intArc.escribir_linea(ced,"\n\t"+Fecha());
                      obj1[0] = resultado.getObject(1);//El primer indice en rs es el 1 no el cero por eso se suma 1
                      obj1[1] = resultado.getObject(2);
                      obj1[2] = resultado.getObject(3);
                      obj1[3] = resultado.getObject(4);
                      for(int i=0;i<3;i++){
                            intArc.escribir_linea(ced,"\t"+ obj1[i].toString());
                      }
                      intArc.escribir_linea(ced,"\tDEVOLUCION");
                  }
              } catch (SQLException ex) {
                  Logger.getLogger(Borrar.class.getName()).log(Level.SEVERE, null, ex);
              }
          p=intCon.borra_prestamos(ced);
          e=intCon.borra_estudiante(ced);
          JOptionPane.showMessageDialog(this, "Registros Borrados:\nEstudiantes: "+String.valueOf(e)+"\nPrestamos: "+String.valueOf(p));
          model.removeRow(tbl_registro.getSelectedRow());
          }
      }else{
          JOptionPane.showMessageDialog(this, "No existen datos seleccionados");
      }
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_borrarMouseClicked

    private void btn_editarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editarMouseClicked
        int fila = tbl_registro.getSelectedRow();
        if (fila != -1) {
            String ced=null;
            Object obj=null;
            DefaultTableModel model = (DefaultTableModel)tbl_registro.getModel();
            obj=model.getValueAt(tbl_registro.getSelectedRow(),0);
            ced=obj.toString();
            Editar instEdt=new Editar(this,true,ced);
            Dimension pantalla=this.getSize();
            instEdt.setSize(pantalla.height/2+700, pantalla.width/2+400);
            instEdt.setLocationRelativeTo(this);
            instEdt.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "No existen datos seleccionados");
        }
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_editarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Borrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Borrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Borrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Borrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Borrar dialog = new Borrar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_borrar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_registro;
    // End of variables declaration//GEN-END:variables
}
