/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.interfase;
import com.negocio.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
/**
 *
 * @author CEC
 */
public class modifica_inventario extends javax.swing.JDialog {

    /**
     * Creates new form modifica_inventario
     */
    public modifica_inventario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_cod = new javax.swing.JTextField();
        btn_buscarcod = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_destino = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_descripcion = new javax.swing.JTextField();
        txt_unidades = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_observacion = new javax.swing.JTextField();
        btn_actualizar = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        btn_borrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        btn_contrasena = new javax.swing.JButton();
        btn_agregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Elemento");

        txt_cod.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        txt_cod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codActionPerformed(evt);
            }
        });

        btn_buscarcod.setText("Buscar");
        btn_buscarcod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_buscarcodMouseClicked(evt);
            }
        });

        jLabel1.setText("Codigo:");

        jLabel2.setText("Destino:");

        txt_nombre.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N

        jLabel3.setText("Nombre:");

        txt_destino.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N

        jLabel4.setText("Descripción:");

        txt_descripcion.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N

        txt_unidades.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N

        jLabel5.setText("Unidades:");

        jLabel6.setText("Observacion:");

        txt_observacion.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N

        btn_actualizar.setText("Actualizar");
        btn_actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_actualizarMouseClicked(evt);
            }
        });

        btn_limpiar.setText("Limpiar");
        btn_limpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_limpiarMouseClicked(evt);
            }
        });

        btn_borrar.setText("Borrar Elemento");
        btn_borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_borrarMouseClicked(evt);
            }
        });

        jLabel7.setText("Cant. Actual:");

        btn_contrasena.setText("Cambiar Contraseña");
        btn_contrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_contrasenaMouseClicked(evt);
            }
        });

        btn_agregar.setText("Agregar Elemento");
        btn_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_contrasena)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_unidades, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(btn_buscarcod))
                            .addComponent(txt_destino, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(txt_observacion))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_nombre)
                                .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_borrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(btn_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btn_buscarcod))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_unidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_observacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscarcodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarcodMouseClicked
        Consulta intcn=new Consulta();
        ResultSet resultado=null;
        if(txt_cod.getText()==null||"".equals(txt_cod.getText())||" ".equals(txt_cod.getText())){
            JOptionPane.showMessageDialog(null, "Ingrese el CODIGO");
        }else{
            resultado=intcn.consulta_elemCod(txt_cod.getText());        
            try {
                if(resultado.next()){                    
                    txt_destino.setText(resultado.getObject(2).toString());
                    txt_nombre.setText(resultado.getObject(3).toString());
                    txt_descripcion.setText(resultado.getObject(4).toString());
                    txt_unidades.setText(resultado.getObject(5).toString());
                    txt_cantidad.setText(resultado.getObject(13).toString());
                    txt_observacion.setText(resultado.getObject(16).toString());
                }
            } catch (SQLException e) {
                System.out.println("Error inesperado: " + e.getMessage());
            }
            txt_cod.enable(false);
        }
    }//GEN-LAST:event_btn_buscarcodMouseClicked

    private void btn_limpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_limpiarMouseClicked
        txt_nombre.setText("");
        txt_destino.setText("");
        txt_descripcion.setText("");
        txt_unidades.setText("");
        txt_cantidad.setText("");
        txt_observacion.setText("");
        txt_cod.setText("");
        txt_cod.enable(true);
    }//GEN-LAST:event_btn_limpiarMouseClicked

    private void btn_actualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actualizarMouseClicked
        Consulta intcn=new Consulta();
        if("".equals(txt_nombre.getText())||"".equals(txt_destino.getText())||"".equals(txt_descripcion.getText())||
                "".equals(txt_unidades.getText())||"".equals(txt_observacion.getText())||"".equals(txt_cod.getText())){
            JOptionPane.showMessageDialog(null, "Uno de los campos esta vacio");
            
        }else{
            int actualiza = intcn.actualiza_Inventario(txt_cod.getText(),txt_destino.getText(),
                    txt_nombre.getText(),  txt_descripcion.getText(), txt_unidades.getText(),txt_cantidad.getText(), txt_observacion.getText());
            JOptionPane.showMessageDialog(this, "Registros Actualizados: "+String.valueOf(actualiza));
        }
        
    }//GEN-LAST:event_btn_actualizarMouseClicked

    private void btn_borrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_borrarMouseClicked
        Consulta intcn=new Consulta();
        if("".equals(txt_nombre.getText())||"".equals(txt_destino.getText())||"".equals(txt_descripcion.getText())||
                "".equals(txt_unidades.getText())||"".equals(txt_observacion.getText())||"".equals(txt_cod.getText())){
            JOptionPane.showMessageDialog(null, "Se debe seleccionar un elemento\nIngrese un codigo");
            
        }else{
            int k =  JOptionPane.showConfirmDialog(rootPane, "Borrar Todos los registros de este elemento??", "BORRAR REGISTROS", JOptionPane.YES_NO_CANCEL_OPTION);
            if(JOptionPane.OK_OPTION==k){
                int actualiza = intcn.borra_Elemento(txt_cod.getText());
                JOptionPane.showMessageDialog(this, "Registros Borrados: "+String.valueOf(actualiza));
                txt_nombre.setText("");
                txt_destino.setText("");
                txt_descripcion.setText("");
                txt_unidades.setText("");
                txt_cantidad.setText("");
                txt_observacion.setText("");
                txt_cod.setText("");
                txt_cod.enable(true);                
            }
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btn_borrarMouseClicked

    private void btn_contrasenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_contrasenaMouseClicked
        Contrasena cn=new Contrasena();
        RSA rsa = new RSA();        
        JPasswordField jpf1 = new JPasswordField();
        JLabel titulo1 = new JLabel ("Ingrese la nueva contraseña");
        JOptionPane.showConfirmDialog (null, new Object[]{titulo1, jpf1}, "Cambiar Contraseña", JOptionPane.OK_CANCEL_OPTION);
        char p1[] = jpf1.getPassword();
        String pass = new String(p1);
        JPasswordField jpf = new JPasswordField();
        JLabel titulo = new JLabel ("Ingrese la nueva contraseña");
        JOptionPane.showConfirmDialog (null, new Object[]{titulo, jpf}, "Cambiar Contraseña", JOptionPane.OK_CANCEL_OPTION);
        char p[] = jpf.getPassword();
        String pass2 = new String(p);
        if(pass.equals(pass2)&&!pass.equals("")){
            cn.cambiar_pass(pass);
            String c=cn.devolver_pss();
            JOptionPane.showMessageDialog(null, "Contraseña cambiada: "+c);
        }else{
             JOptionPane.showMessageDialog(null, "Las contraseñas no coincidieron");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_contrasenaMouseClicked

    private void txt_codActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codActionPerformed
        txt_cod.addKeyListener(new MakeEnterDoAction());
        Consulta intcn=new Consulta();
        ResultSet resultado=null;
        if(txt_cod.getText()==null||"".equals(txt_cod.getText())||" ".equals(txt_cod.getText())){
            JOptionPane.showMessageDialog(null, "Ingrese el CODIGO");
        }else{
            resultado=intcn.consulta_elemCod(txt_cod.getText());        
            try {
                if(resultado.next()){                    
                    txt_destino.setText(resultado.getObject(2).toString());
                    txt_nombre.setText(resultado.getObject(3).toString());
                    txt_descripcion.setText(resultado.getObject(4).toString());
                    txt_unidades.setText(resultado.getObject(5).toString());
                    txt_cantidad.setText(resultado.getObject(13).toString());
                    txt_observacion.setText(resultado.getObject(16).toString());
                }
            } catch (SQLException e) {
                System.out.println("Error inesperado: " + e.getMessage());
            }
            txt_cod.enable(false);
        }// TODO add your handling code here:
    }//GEN-LAST:event_txt_codActionPerformed

    private void btn_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarMouseClicked
        Consulta intcn=new Consulta();
        if("".equals(txt_nombre.getText())||"".equals(txt_destino.getText())||"".equals(txt_descripcion.getText())||
                "".equals(txt_unidades.getText())||"".equals(txt_observacion.getText())||"".equals(txt_cod.getText())){
            JOptionPane.showMessageDialog(null, "Uno de los campos esta vacio");
            
        }else{
            int agrega = intcn.escribe_Inventario(txt_cod.getText(),txt_destino.getText(),
                    txt_nombre.getText(),  txt_descripcion.getText(), txt_unidades.getText(),txt_cantidad.getText(), txt_observacion.getText());
            JOptionPane.showMessageDialog(this, "Registros Actualizados: "+String.valueOf(agrega));
        }// TODO add your handling code here:
    }//GEN-LAST:event_btn_agregarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modifica_inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modifica_inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modifica_inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modifica_inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                modifica_inventario dialog = new modifica_inventario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_borrar;
    private javax.swing.JButton btn_buscarcod;
    private javax.swing.JButton btn_contrasena;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_cod;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_destino;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_observacion;
    private javax.swing.JTextField txt_unidades;
    // End of variables declaration//GEN-END:variables
}
