/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.interfase;

import com.negocio.Contrasena;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.awt.image.ImageObserver;
import java.awt.image.ImageProducer;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author tutor
 */
public class Pricipal extends javax.swing.JFrame {

    /**
     * Creates new form Pricipal
     */
    public Pricipal() {
        initComponents();
    }

    
    @Override
    public Image getIconImage(){
        Image retVal=Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("com/resources/utemct.jpg"));
        return retVal;
    }   
    /*
    public Image getIconImage(){
        Image retVal=Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("com/resources/utemct.jpg"));
        return retVal;
    } */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_ingresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_borrar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_recordatorios = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mn_barra = new javax.swing.JMenuBar();
        mn_archivo = new javax.swing.JMenu();
        mn_inventario = new javax.swing.JMenuItem();
        mn_salir = new javax.swing.JMenuItem();
        mn_acerca = new javax.swing.JMenu();
        mn_acerca1 = new javax.swing.JMenuItem();
        mn_agradecimientos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LabLEND 1.0");
        setBackground(new java.awt.Color(51, 153, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setIconImage(getIconImage());
        setMaximumSize(new java.awt.Dimension(630, 345));
        setMinimumSize(new java.awt.Dimension(630, 345));
        setPreferredSize(new java.awt.Dimension(630, 345));
        getContentPane().setLayout(null);

        btn_ingresar.setText("INGRESAR PRESTAMO");
        btn_ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ingresarMouseClicked(evt);
            }
        });
        getContentPane().add(btn_ingresar);
        btn_ingresar.setBounds(410, 130, 180, 23);

        jLabel1.setFont(new java.awt.Font("Lao UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SISTEMA DE PRESTAMOS");
        jLabel1.setFocusable(false);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 10, 263, 25);
        jLabel1.getAccessibleContext().setAccessibleDescription("");

        btn_borrar.setText("PRESTAMOS, ESTUDIANTES");
        btn_borrar.setToolTipText("");
        btn_borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_borrarMouseClicked(evt);
            }
        });
        getContentPane().add(btn_borrar);
        btn_borrar.setBounds(410, 230, 180, 23);

        btn_editar.setText("EDITAR PRESTAMO");
        btn_editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editarMouseClicked(evt);
            }
        });
        getContentPane().add(btn_editar);
        btn_editar.setBounds(410, 180, 180, 23);

        btn_recordatorios.setText("RECORDATORIOS");
        btn_recordatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_recordatoriosMouseClicked(evt);
            }
        });
        getContentPane().add(btn_recordatorios);
        btn_recordatorios.setBounds(410, 280, 180, 23);

        jLabel2.setFont(new java.awt.Font("Lao UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MECATRÓNICA UTE");
        jLabel2.setFocusable(false);
        jLabel2.setMaximumSize(new java.awt.Dimension(610, 345));
        jLabel2.setMinimumSize(new java.awt.Dimension(610, 345));
        jLabel2.setPreferredSize(new java.awt.Dimension(610, 345));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(390, 40, 210, 26);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resources/brazo.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 390, 330);

        mn_archivo.setText("Archivo");

        mn_inventario.setText("Editar Elemento en Inventario...");
        mn_inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_inventarioActionPerformed(evt);
            }
        });
        mn_archivo.add(mn_inventario);

        mn_salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK));
        mn_salir.setText("Salir");
        mn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_salirActionPerformed(evt);
            }
        });
        mn_archivo.add(mn_salir);

        mn_barra.add(mn_archivo);

        mn_acerca.setText("Acerca de....");
        mn_acerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_acercaActionPerformed(evt);
            }
        });

        mn_acerca1.setText("Acerca de...");
        mn_acerca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_acerca1ActionPerformed(evt);
            }
        });
        mn_acerca.add(mn_acerca1);

        mn_agradecimientos.setText("Agradecimientos");
        mn_agradecimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_agradecimientosActionPerformed(evt);
            }
        });
        mn_acerca.add(mn_agradecimientos);

        mn_barra.add(mn_acerca);

        setJMenuBar(mn_barra);

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingresarMouseClicked
        Ingresar instIng=new Ingresar(this,true);
        Dimension pantalla=this.getSize();
        instIng.setSize(pantalla.height/2+700, pantalla.width/2+400);
        instIng.setLocationRelativeTo(this);
        instIng.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_btn_ingresarMouseClicked

    private void btn_borrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_borrarMouseClicked
        Borrar instbor=new Borrar(this,true);
        Dimension pantalla=this.getSize();
        instbor.setSize(pantalla.height/2+600, pantalla.width/2+150);
        instbor.setLocationRelativeTo(this);
        instbor.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btn_borrarMouseClicked

    private void btn_editarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editarMouseClicked
        Editar instEdt=new Editar(this,true);
        Dimension pantalla=this.getSize();
        instEdt.setSize(pantalla.height/2+700, pantalla.width/2+400);
        instEdt.setLocationRelativeTo(this);
        instEdt.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_btn_editarMouseClicked

    private void btn_recordatoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_recordatoriosMouseClicked
      // new Recordatorios(this, true).setVisible(true);
        Recordatorios instRec=new Recordatorios(this,true);
        Dimension pantalla=this.getSize();
        instRec.setSize(pantalla.height/2+600, pantalla.width/2+200);
        instRec.setLocationRelativeTo(this);
        instRec.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btn_recordatoriosMouseClicked

    private void mn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_salirActionPerformed
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_mn_salirActionPerformed

    private void mn_acerca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_acerca1ActionPerformed
        ImageIcon icono  =  new ImageIcon(ClassLoader.getSystemResource("com/resources/repara.png"));
        JOptionPane.showMessageDialog(null, "SISTEMA DE PRESTAMOS\nLABORATORIO DE MECATRONICA\nUTE\n\nVersion 1.0.0.1\nc DVEGAP2013","Acerca de LabLEND 1.0",JOptionPane.PLAIN_MESSAGE,icono);// TODO add your handling code here:
    }//GEN-LAST:event_mn_acerca1ActionPerformed

    private void mn_acercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_acercaActionPerformed
        
    }//GEN-LAST:event_mn_acercaActionPerformed

    private void mn_agradecimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_agradecimientosActionPerformed
        ImageIcon icono  =  new ImageIcon(ClassLoader.getSystemResource("com/resources/Imagen3.png"));
        JOptionPane.showMessageDialog(null, "CREADO POR:\nDAVID ALEJANDRO VEGA PEREZ\nIngenieria Mecatrónica\nUTE\n\nAgradecimientos:\nDr. Daniel Mideros\nIng. Anibal Mantilla\n\n2013\ndavidvegap@hotmail.com","Agradecimientos",JOptionPane.INFORMATION_MESSAGE,icono);// TODO add your handling code here
    }//GEN-LAST:event_mn_agradecimientosActionPerformed

    private void mn_inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_inventarioActionPerformed
        Contrasena cn=new Contrasena();
        String contrasena=cn.devolver_pss();
        JPasswordField jpf = new JPasswordField();
        JLabel titulo = new JLabel ("Ingrese la contraseña para poder continuar:");        
        JOptionPane.showConfirmDialog (null, new Object[]{titulo, jpf}, "Editar Inventario", JOptionPane.OK_CANCEL_OPTION);
        char p[] = jpf.getPassword();
        String pass = new String(p);
        if(pass.equals(contrasena)){
            JOptionPane.showMessageDialog (null, "\nContraseña correcta....\nAutorizado" );
            modifica_inventario instMod=new modifica_inventario(this,true);
            Dimension pantalla=this.getSize();
            instMod.setSize(pantalla.height/2+250, pantalla.width/2+180);
            instMod.setLocationRelativeTo(this);
            instMod.setVisible(true);
            
        }else{
            JOptionPane.showMessageDialog (null, "\nContraseña Incorrecta...." + pass);
        }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_mn_inventarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pricipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pricipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pricipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pricipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dimension pantalla=Toolkit.getDefaultToolkit().getScreenSize();
                Pricipal instprincipal=new Pricipal();
                instprincipal.setSize(pantalla.width/2+25, pantalla.height/2+10);
                instprincipal.setLocationRelativeTo(null);
                instprincipal.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_borrar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JButton btn_recordatorios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu mn_acerca;
    private javax.swing.JMenuItem mn_acerca1;
    private javax.swing.JMenuItem mn_agradecimientos;
    private javax.swing.JMenu mn_archivo;
    private javax.swing.JMenuBar mn_barra;
    private javax.swing.JMenuItem mn_inventario;
    private javax.swing.JMenuItem mn_salir;
    // End of variables declaration//GEN-END:variables

    
}
