/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.interfase;

import com.negocio.Consulta;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tutor
 */
public class Recordatorios extends javax.swing.JDialog {

    /**
     * Creates new form Recordatorios
     */
    public Recordatorios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        String fecha = null;
        Date d = new Date();
        SimpleDateFormat sdf= new SimpleDateFormat("dd-MM-yyyy h:mm a");
        fecha=sdf.format(d).toString();
        txt_fecha.setText(fecha);
        ResultSet resultado=null;
        Consulta instconsulta= new Consulta();
        resultado= instconsulta.realiza_Consulta("recordatorios");
        DefaultTableModel searchListModel = new DefaultTableModel();
        this.tbl_record.setModel(searchListModel);
        searchListModel.addColumn("FECHA");
        searchListModel.addColumn("RECORDATORIO");        
        //ASIGNAR TAMAÑO A CADA COLUMNA
        tbl_record.getColumnModel().getColumn(0).setPreferredWidth(25);
        tbl_record.getColumnModel().getColumn(1).setPreferredWidth(200);
        try{
            while(resultado.next()){
                //Se crea un array q sera una de las filas de la tabla
                Object [] fila = new Object[2];//Hay 4 columnas en la tabla
                for(int i=1; i<=2;i++){
                    fila[i-1] = resultado.getObject(i);
                }//El primer indice en rs es el 1 no el cero por eso se suma 1
                // Se añade al modelo la Fila completa
                searchListModel.addRow(fila);
            }
        }catch(SQLException e){
            System.out.println("Error de MySQL: "+e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_fecha = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_recordatorio = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_record = new javax.swing.JTable();
        btn_guardar = new javax.swing.JButton();
        btn_borrar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LabLEND 1.0 - Recordatorios");

        jLabel1.setText("Hora:");

        txt_fecha.setEditable(false);
        txt_fecha.setText("jTextField1");

        jLabel2.setText("Recordatorio:");

        txt_recordatorio.setColumns(20);
        txt_recordatorio.setRows(5);
        jScrollPane1.setViewportView(txt_recordatorio);

        tbl_record.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbl_record);

        btn_guardar.setText("Guardar");
        btn_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_guardarMouseClicked(evt);
            }
        });

        btn_borrar.setText("Borrar Recordatorio");
        btn_borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_borrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btn_guardar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_borrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_borrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_borrarMouseClicked
        int fila = tbl_record.getSelectedRow();
        if (fila != -1) {
          int k =  JOptionPane.showConfirmDialog(rootPane, "Borrar Recordatorio??", "BORRAR RECORDATORIO", 1);
          if(JOptionPane.OK_OPTION==k){
            String fecha=null;
            Object obj=null;
            Consulta intCon=new Consulta();
            DefaultTableModel model = (DefaultTableModel)tbl_record.getModel();        
            obj=model.getValueAt(tbl_record.getSelectedRow(),0);
            fecha=obj.toString();
            int rb=intCon.borra_Recordatorio(fecha);            
            JOptionPane.showMessageDialog(this, "Registros Borrados "+String.valueOf(rb));
            model.removeRow(tbl_record.getSelectedRow());
            }
        }else{
            JOptionPane.showMessageDialog(this, "No existen datos seleccionados");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_borrarMouseClicked

    private void btn_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarMouseClicked
        Consulta instC=new Consulta();
        if(txt_recordatorio.getText()==null||"".equals(txt_recordatorio.getText())||" ".equals(txt_recordatorio.getText())){
            JOptionPane.showMessageDialog(null, "Campo recordatorio es obligatorio");
        }else{
            instC.ingresa_Recordatorio(txt_fecha.getText(),txt_recordatorio.getText());
            int r=0;
            int n =tbl_record.getRowCount();
            int c =tbl_record.getColumnCount();
            Object[] filaSeleccionada;
            filaSeleccionada = new Object[c];
            DefaultTableModel searchListModel;
            searchListModel = (DefaultTableModel)tbl_record.getModel();
            filaSeleccionada[0]=txt_fecha.getText();
            filaSeleccionada[1]=txt_recordatorio.getText();
            searchListModel.addRow(filaSeleccionada);
        }// TODO add your handling code here:
    }//GEN-LAST:event_btn_guardarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recordatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recordatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recordatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recordatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Recordatorios dialog = new Recordatorios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_borrar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tbl_record;
    private javax.swing.JTextField txt_fecha;
    private javax.swing.JTextArea txt_recordatorio;
    // End of variables declaration//GEN-END:variables
}
